project_name: muxie

before:
  hooks:
    - go mod tidy

builds:
  - id: muxie
    main: .
    binary: muxie
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/MSmaili/muxie/cmd.Version={{.Version}}
      - -X github.com/MSmaili/muxie/cmd.GitCommit={{.ShortCommit}}
      - -X github.com/MSmaili/muxie/cmd.BuildDate={{.Date}}

archives:
  - id: muxie
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- .Arch }}
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: MSmaili
    name: muxie
  draft: false
  prerelease: auto
